library(dplyr)

assign_var_category <- function(df) {
    df |>
        mutate(
            var_category =
                case_when(
                    variable %in%
                        c(
                            "pop_density", "pop_nr_est", "pop_prcnt_est_15to24_allRaces_m",
                            "pop_prcnt_est_15to24_b_m", "pop_prcnt_est_15to24_h_m",
                            "pop_prcnt_est_allAges_b", "pop_prcnt_est_allAges_h",
                            "pop_prcnt_est_allAges_w", "% Black", "% Hisp.",
                            "Racial/ethnic diversity", "delta_index_black",
                            "delta_index_hisp", "delta_index_white",
                            "dissimilarity_index_WhiteBlack", "dissimilarity_index_WhiteHisp",
                            "multigroup_entropy_race", "norm_exposure_index_WhiteBlack",
                            "norm_exposure_index_WhiteHisp", "spatial_proximity_race_b001",
                            "spatial_proximity_race_b01", "gini_simpson_index",
                            "lq_black", "lq_hisp", "lq_white", "shannon_index_scaled",
                            "Dissimilarity Index (Race)", "Spatial Proximity (Race)",
                            "Population + Exposure Index", "Delta Index (Race, Education, Income)"
                        ) ~ "Racial/ethnic diversity + Segregation",
                    variable %in%
                        c(
                            "hhIncome_median_est", "hhIncomebelow30_prcnt_est",
                            "hhIncomefrom30to60_prcnt_est", "hhIncomefrom60to100_prcnt_est",
                            "hhIncomefrom100to150_prcnt_est", "poverty_prcnt_est_allAges",
                            "ratioIncomeToPovertyBelow75_prcnt_est_povertyUniverse",
                            "ratioIncomeToPoverty75to99_prcnt_est_povertyUniverse",
                            "ratioIncomeToPoverty100to124_prcnt_est_povertyUniverse",
                            "ratioIncomeToPoverty125to149_prcnt_est_povertyUniverse",
                            "ratioIncomeToPoverty150to174_prcnt_est_povertyUniverse",
                            "ratioIncomeToPoverty175to199_prcnt_est_povertyUniverse",
                            "hhReceiveCpaSnap_prcnt_est",
                            "poverty_prcnt_est_0to17",
                            "receiveCpaSnapSSI_prcnt_est_ages17AndYounger",
                            "Deep Poverty", "Poverty + Low Education",
                            "epr_prcnt_est_16andOlder", "lfpr_prcnt_est_16andOlder",
                            "ur_prcnt_est_16andOlder", "hs_prcnt_est_25older",
                            "lessThanHs_prcnt_est_25older",
                            "someCollege_prcnt_est_25older",
                            "notInSchoolOrLf_prcnt_est_ages16to19", "Poverty",
                            "Work force participation", "Work Participation + Vacant Housing"
                        ) ~ "Socioeconomic Status",
                    variable %in%
                        c(
                            "giniCoefficient_index_est", "hhShareOfIncome_1stQuintile_est",
                            "hhShareOfIncome_2ndQuintile_est", "hhShareOfIncome_3rdQuintile_est",
                            "hhShareOfIncome_4thQuintile_est", "hhShareOfIncome_top5Prcnt_est",
                            "Concentrated Wealth", "Income Inequality"
                        ) ~ "Income Inequality",
                    variable %in%
                        c(
                            "grossMortgagePrcntIncome_median_est",
                            "grossRentPrcntIncome_median_est",
                            "hhCostsBetween10and15PrcntIncome_prcnt_est",
                            "hhCostsBetween15and20PrcntIncome_prcnt_est",
                            "hhCostsBetween20and25PrcntIncome_prcnt_est",
                            "hhCostsBetween25and30PrcntIncome_prcnt_est",
                            "hhCostsBetween30and35PrcntIncome_prcnt_est",
                            "hhCostsBetween35and40PrcntIncome_prcnt_est",
                            "hhCostsBetween40and50PrcntIncome_prcnt_est",
                            "hhCostsAbove50PrcntIncome_prcnt_est",
                            "hhCostsPrcntIncome_median_est",
                            "hhBetweeen51and100PersonPerRoom_prcnt_est",
                            "hhBetweeen101and150PersonPerRoom_prcnt_est",
                            "hhBetweeen151and200PersonPerRoom_prcnt_est",
                            "hhAbove200PersonPerRoom_prcnt_est",
                            "hhBathroomProblems_prcnt_est",
                            "hhKitchenProblems_prcnt_est",
                            "hhNoPhone_prcnt_est",
                            "hhWith1Problem_prcnt_est",
                            "hhWith2Problem_prcnt_est",
                            "hhWith3Problem_prcnt_est",
                            "hhWith4Problem_prcnt_est",
                            "vacantHousingUnits_prcnt_est", "Low/High Housing Costs",
                            "Moderately High Housing Costs", "Not Overcrowded",
                            "Rent burdened", "Low Housing Costs"
                        ) ~ "Housing Costs + Quality",
                    variable %in%
                        c(
                            "hhLessThan50Value_prcnt_est",
                            "hhBetween50And100Value_prcnt_est",
                            "hhBetween100And150Value_prcnt_est",
                            "hhBetween150And200Value_prcnt_est",
                            "hhBetween200And300Value_prcnt_est",
                            "hhBetween300And500Value_prcnt_est",
                            "hhBetween500And1000Value_prcnt_est",
                            "hhOwns1Vehicle_prcnt_est", "hhOwns2Vehicle_prcnt_est",
                            "hhOwns3Vehicle_prcnt_est", "hhOwns4Vehicle_prcnt_est",
                            "hhOwnsNoVehicle_prcnt_est", "homeValue_25thPtile_est",
                            "homeValue_median_est", "homeValue_75thPtile_est",
                            "liveInRental_prcnt_est_allAges", "Home Values",
                            "Low/High Vehicle Ownership"
                        ) ~ "Wealth",
                    variable %in%
                        c(
                            "everMarried_prcnt_est_15andOlder",
                            "marriageNotSeparated_prcnt_est_15andOlder",
                            "singleMom_prcnt_est", "singleParent_prcnt_est",
                            "doNotLiveWithParent_prcnt_est_ages17AndYounger",
                            "liveInSingleParentHh_prcnt_est_ages17AndYounger",
                            "Marriage", "Single Parent HH", "yearMoved_median_est",
                            "movedPastYear_prcnt_est_1AndOlder", "Residential Stability"
                        ) ~ "Family Composition + Residential Stability",
                    variable %in%
                        c(
                            "nr_businesses_per10k", "nr_new_businesses_per10k",
                            "nr_socialAssociations_max_per10k", "nr_socialAssociations_min_per10k",
                            "nr_socialSupportServices_max_per10k", "nr_socialSupportServices_min_per10k",
                            "nr_allSocialBeautyBusinesses_max_per10k", "nr_allSocialBeautyBusinesses_min_per10k",
                            "Nr. Social Support Services", "Nr. Total Social Capital Orgs.",
                            "Nr. Social Associations"
                        ) ~ "Social capital + Business Environment",
                    variable %in%
                        c(
                            "all_crimes_per100k", "property_crime_per100k",
                            "violent_crime_per100k", "nr_homicides_max_per100k",
                            "nr_homicides_min_per100k", "nr_homicides_max_3yr_avg_per100k",
                            "nr_homicides_min_3yr_avg_per100k", "nr_homicides_max_5yr_avg_per100k",
                            "nr_homicides_min_5yr_avg_per100k", "Crime",
                            "Homicides", "Homicides (Max Averaged)",
                            "Homicides (Min Averaged)", "Property Crime"
                        ) ~ "Violence + Crime",
                    variable %in%
                        c(
                            "blackToWhiteChildPoverty_diff_est",
                            "blackToWhiteCollege_diff_est",
                            "blackToWhiteEverMarried_diff_est",
                            "blackToWhiteMarried_diff_est",
                            "blackToWhiteMovers_diff_est",
                            "blackToWhitePoverty_diff_est",
                            "blackToWhiteRenters_diff_est",
                            "blackToWhiteSingleMom_diff_est",
                            "blackToWhiteSingleParent_diff_est",
                            "blackToWhiteUnmarriedBirthRate_diff_est",
                            "hhSnapBlackToWhite_diff_est",
                            "ratioBlackWhiteOvercrowding_diff_est",
                            "urBlackToWhite_diff_est_16andOlder",
                            "lfprBlackToWhite_diff_est_16andOlder",
                            "medianHhIncomeBlackToWhite_prcnt_est",
                            "Black v. White Poverty", "Black v. White Single Parent"
                        ) ~ "Racial Differences (Black vs. White)",
                    variable %in%
                        c(
                            "hispToWhiteChildPoverty_diff_est",
                            "hispToWhiteCollege_diff_est",
                            "hispToWhiteEverMarried_diff_est",
                            "hispToWhiteMarried_diff_est",
                            "hispToWhiteMovers_diff_est",
                            "hispToWhitePoverty_diff_est",
                            "hispToWhiteRenters_diff_est",
                            "hispToWhiteSingleMom_diff_est",
                            "hispToWhiteSingleParent_diff_est",
                            "hispToWhiteUnmarriedBirthRate_diff_est",
                            "hhSnapHispToWhite_diff_est",
                            "ratioHispWhiteOvercrowding_diff_est",
                            "urHispToWhite_diff_est_16andOlder",
                            "lfprHispToWhite_diff_est_16andOlder",
                            "medianHhIncomeHispToWhite_prcnt_est",
                            "Hisp. v. White Poverty", "Hisp. v. White Single Parent"
                        ) ~ "Racial Differences (Hispanic vs. White)",
                    variable %in%
                        c(
                            "delta_index_income", "dissimilarity_index_hhIncome",
                            "multigroup_entropy_hhIncome", "norm_exposure_index_hhIncome",
                            "spatial_proximity_income_b001", "spatial_proximity_income_b01",
                            "gini_simpson_index_hhIncome", "shannon_index_scaled_hhIncome",
                            "Income diversity", "Spatial Proximity (Income)",
                            "delta_index_edu", "dissimilarity_index_edu",
                            "multigroup_entropy_edu", "norm_exposure_index_edu",
                            "spatial_proximity_edu_b001", "spatial_proximity_edu_b01",
                            "gini_simpson_index_edu", "shannon_index_scaled_edu",
                            "Educational diversity", "Spatial Proximity (Education)",
                            "Dissimilarity Index (Education, Income)"
                        ) ~ "Socioeconomic Segregation + Diversity",
                    variable %in%
                        c(
                            "governor", "h_chamber_sd", "h_dem_sd", "h_distance",
                            "h_rep_sd", "hou_chamber", "hou_dem", "hou_dem_mean",
                            "hou_rep", "hou_rep_mean", "president", "s_chamber_sd",
                            "s_dem_sd", "s_distance", "s_rep_sd", "sen_chamber",
                            "sen_dem", "sen_dem_mean", "sen_rep", "sen_rep_mean",
                            "senate", "lq_governor", "lq_president", "lq_senate",
                            "% Republican", "% Uniquely Republican", "Political Polarization",
                            "State-level Democratic ideology", "State-level political ideology",
                            "State-level Republican ideology"
                        ) ~ "Political Ideology",
                    variable == "total_prison_adm_rate15to64" ~ "Outcome"
                )
        )
}

std_var_names <- function(df) {
    df |>
        mutate(
            variable =
                case_when(
                    variable == "all_crimes_per100k" ~ "Nr. of crimes per 100k individuals",
                    variable == "blackToWhiteChildPoverty_diff_est" ~ "B. vs. W. child poverty %",
                    variable == "blackToWhiteCollege_diff_est" ~ "B. vs. W. college graduation %",
                    variable == "blackToWhiteEverMarried_diff_est" ~ "B. vs. W. ever-married %",
                    variable == "blackToWhiteMarried_diff_est" ~ "B. vs. W. married %",
                    variable == "blackToWhiteMovers_diff_est" ~ "B. vs. W. moved in past year %",
                    variable == "blackToWhitePoverty_diff_est" ~ "B. vs. W. poverty %",
                    variable == "blackToWhiteRenters_diff_est" ~ "B. vs. W. renter %",
                    variable == "blackToWhiteSingleMom_diff_est" ~ "B. vs. W. single-mother %",
                    variable == "blackToWhiteSingleParent_diff_est" ~ "B. vs. W. single-parent %",
                    variable == "blackToWhiteUnmarriedBirthRate_diff_est" ~ "B. vs. W. unmarried birthrate %",
                    variable == "hhSnapBlackToWhite_diff_est" ~ "B. vs. W. HH SNAP participation %",
                    variable == "hispToWhiteChildPoverty_diff_est" ~ "H. vs. W. child poverty %",
                    variable == "hispToWhiteCollege_diff_est" ~ "H. vs. W. college graduation %",
                    variable == "hispToWhiteEverMarried_diff_est" ~ "H. vs. W. ever-married %",
                    variable == "hispToWhiteMarried_diff_est" ~ "H. vs. W. married %",
                    variable == "hispToWhiteMovers_diff_est" ~ "H. vs. W. moved in past year %",
                    variable == "hispToWhitePoverty_diff_est" ~ "H. vs. W. poverty %",
                    variable == "hispToWhiteRenters_diff_est" ~ "H. vs. W. renter %",
                    variable == "hispToWhiteSingleMom_diff_est" ~ "H. vs. W. single-mother %",
                    variable == "hispToWhiteSingleParent_diff_est" ~ "H. vs. W. single-parent %",
                    variable == "hispToWhiteUnmarriedBirthRate_diff_est" ~ "H. vs. W. unmarried birthrate %",
                    variable == "hhSnapHispToWhite_diff_est" ~ "H. vs. W. HH SNAP participation %",
                    variable == "delta_index_black" ~ "Delta Index (Black)",
                    variable == "delta_index_edu" ~ "Delta Index (Education)",
                    variable == "delta_index_hisp" ~ "Delta Index (Hispanic)",
                    variable == "delta_index_income" ~ "Delta Index (HH Income)",
                    variable == "delta_index_white" ~ "Delta Index (White)",
                    variable == "dissimilarity_index_edu" ~ "Dissimilarity Index (Education)",
                    variable == "dissimilarity_index_hhIncome" ~ "Dissimilarity Index (HH Income)",
                    variable == "dissimilarity_index_WhiteBlack" ~ "Dissimilarity Index (W. vs. B.)",
                    variable == "dissimilarity_index_WhiteHisp" ~ "Dissimilarity Index (W. vs. H.)",
                    variable == "doNotLiveWithParent_prcnt_est_ages17AndYounger" ~ "% of children who do not live w/ parent",
                    variable == "epr_prcnt_est_16andOlder" ~ "Employment-Population Ratio",
                    variable == "everMarried_prcnt_est_15andOlder" ~ "% ever-married",
                    variable == "gini_simpson_index" ~ "Gini-Simpson Index (Race)",
                    variable == "gini_simpson_index_edu" ~ "Gini-Simpson Index (Education)",
                    variable == "gini_simpson_index_hhIncome" ~ "Gini-Simpson Index (HH Income)",
                    variable == "giniCoefficient_index_est" ~ "Gini coefficient",
                    variable == "governor" ~ "% voted R. in most recent gubernatorial election",
                    variable == "grossMortgagePrcntIncome_median_est" ~ "Mortgage as % of Income (Median)",
                    variable == "grossRentPrcntIncome_median_est" ~ "Rent as % of Income (Median)",
                    variable == "h_chamber_sd" ~ "Std. Dev. of Ideology in State House",
                    variable == "h_dem_sd" ~ "Std. Dev. of D. Ideology in State House",
                    variable == "h_distance" ~ "Mean Ideological Distance in State House",
                    variable == "h_rep_sd" ~ "Std. Dev. of R. Ideology in State House",
                    variable == "hou_chamber" ~ "Median Ideology in State House",
                    variable == "hou_dem" ~ "Median D. Ideology in State House",
                    variable == "hou_dem_mean" ~ "Mean D. Ideology in State House",
                    variable == "hou_rep" ~ "Median R. Ideology in State House",
                    variable == "hou_rep_mean" ~ "Mean R. Ideology in State House",
                    variable == "hhBetweeen51and100PersonPerRoom_prcnt_est" ~ "% of HHs w/ 0.51 to 1 people per room",
                    variable == "hhBetweeen101and150PersonPerRoom_prcnt_est" ~ "% of HHs w/ 1.01 to 1.5 people per room",
                    variable == "hhBetweeen151and200PersonPerRoom_prcnt_est" ~ "% of HHs w/ 1.51 to 1.99 people per room",
                    variable == "hhAbove200PersonPerRoom_prcnt_est" ~ "% of HHs w/ > 2 people per room",
                    variable == "hhLessThan50Value_prcnt_est" ~ "% of homes worth less than $50,000",
                    variable == "hhBetween50And100Value_prcnt_est" ~ "% of homes worth $50,000 - $99,999",
                    variable == "hhBetween100And150Value_prcnt_est" ~ "% of homes worth $100,000 - $149,999",
                    variable == "hhBetween150And200Value_prcnt_est" ~ "% of homes worth $150,000 - $199,999",
                    variable == "hhBetween200And300Value_prcnt_est" ~ "% of homes worth $200,000 - $299,999",
                    variable == "hhBetween300And500Value_prcnt_est" ~ "% of homes worth $300,000 - $499,999",
                    variable == "hhBetween500And1000Value_prcnt_est" ~ "% of homes worth $500,000 - $999,999",
                    variable == "homeValue_25thPtile_est" ~ "Home Values (25th percentile)",
                    variable == "homeValue_median_est" ~ "Home Values (Median)",
                    variable == "homeValue_75thPtile_est" ~ "Home Values (75th percentile)",
                    variable == "hhBathroomProblems_prcnt_est" ~ "% of HHs lacking complete plumbing",
                    variable == "hhKitchenProblems_prcnt_est" ~ "% of HHs lacking complete kitchen",
                    variable == "hhNoPhone_prcnt_est" ~ "% of HHs lacking a phone",
                    variable == "hhOwnsNoVehicle_prcnt_est" ~ "% of HHs with 0 vehicles",
                    variable == "hhOwns1Vehicle_prcnt_est" ~ "% of HHs with 1 vehicles",
                    variable == "hhOwns2Vehicle_prcnt_est" ~ "% of HHs with 2 vehicles",
                    variable == "hhOwns3Vehicle_prcnt_est" ~ "% of HHs with 3 vehicles",
                    variable == "hhOwns4Vehicle_prcnt_est" ~ "% of HHs with 4 vehicles",
                    variable == "hhCostsBetween10and15PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 10% - 14.9% of income",
                    variable == "hhCostsBetween15and20PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 15% - 19.9% of income",
                    variable == "hhCostsBetween20and25PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 20% - 24.9% of income",
                    variable == "hhCostsBetween25and30PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 25% - 29.9% of income",
                    variable == "hhCostsBetween30and35PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 30% - 34.9% of income",
                    variable == "hhCostsBetween35and40PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 35% - 39.9% of income",
                    variable == "hhCostsBetween40and50PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs between 40% - 49.9% of income",
                    variable == "hhCostsAbove50PrcntIncome_prcnt_est" ~ "% of HHs w/ HH costs 50% or more of income",
                    variable == "hhWith1Problem_prcnt_est" ~ "% of HHs w/ 1 problem",
                    variable == "hhWith2Problem_prcnt_est" ~ "% of HHs w/ 2 problems",
                    variable == "hhWith3Problem_prcnt_est" ~ "% of HHs w/ 3 problems",
                    variable == "hhWith4Problem_prcnt_est" ~ "% of HHs w/ 4 problems",
                    variable == "hhCostsPrcntIncome_median_est" ~ "HH costs as a % of HH income (median)",
                    variable == "hhIncomebelow30_prcnt_est" ~ "% of HHs w/ income below $30,000",
                    variable == "hhIncomefrom30to60_prcnt_est" ~ "% of HHs w/ income between $30,000 - $59,999",
                    variable == "hhIncomefrom60to100_prcnt_est" ~ "% of HHs w/ income between 60,000 - $99,999",
                    variable == "hhIncomefrom100to150_prcnt_est" ~ "% of HHs w/ income between $100,000 - $149,999",
                    variable == "hhReceiveCpaSnap_prcnt_est" ~ "% of HHs receiving cash public assistance or SNAP",
                    variable == "hhShareOfIncome_1stQuintile_est" ~ "% of total HH income held by lowest quintile",
                    variable == "hhShareOfIncome_2ndQuintile_est" ~ "% of total HH income held by 2nd quintile",
                    variable == "hhShareOfIncome_3rdQuintile_est" ~ "% of total HH income held by 3rd quintile",
                    variable == "hhShareOfIncome_4thQuintile_est" ~ "% of total HH income held by 4th quintile",
                    variable == "hhShareOfIncome_top5Prcnt_est" ~ "% of total HH income held by top 5%",
                    variable == "hs_prcnt_est_25older" ~ "% w/ high school education (highest)",
                    variable == "lessThanHs_prcnt_est_25older" ~ "% w/ less than a high school education",
                    variable == "lfpr_prcnt_est_16andOlder" ~ "Labor Force Participation Rate",
                    variable == "lfprBlackToWhite_diff_est_16andOlder" ~ "B. vs. W. Labor Force Participation Rate",
                    variable == "lfprHispToWhite_diff_est_16andOlder" ~ "H. vs. W. Labor Force Participation Rate",
                    variable == "liveInRental_prcnt_est_allAges" ~ "% live in rental",
                    variable == "liveInSingleParentHh_prcnt_est_ages17AndYounger" ~ "% of children who live in single-parent HH",
                    variable == "lq_black" ~ "Location Quotient (Black)",
                    variable == "lq_governor" ~ "Location Quotient (% who voted for R. governor)",
                    variable == "lq_hisp" ~ "Location Quotient (Hispanic)",
                    variable == "lq_president" ~ "Location Quotient (% who voted for R. president)",
                    variable == "lq_senate" ~ "Location Quotient (% who voted for R. senate)",
                    variable == "lq_white" ~ "Location Quotient (White)",
                    variable == "marriageNotSeparated_prcnt_est_15andOlder" ~ "% married",
                    variable == "medianHhIncomeBlackToWhite_prcnt_est" ~ "B. vs. W. (% difference in median income)",
                    variable == "medianHhIncomeHispToWhite_prcnt_est" ~ "H. vs. W. (% difference in median income)",
                    variable == "movedPastYear_prcnt_est_1AndOlder" ~ "% moved in past year",
                    variable == "multigroup_entropy_edu" ~ "Multigroup entropy (education)",
                    variable == "multigroup_entropy_hhIncome" ~ "Multigroup entropy (HH Income)",
                    variable == "multigroup_entropy_race" ~ "Multigroup entropy (Race)",
                    variable == "norm_exposure_index_edu" ~ "Normalized Exposure Index (education)",
                    variable == "norm_exposure_index_hhIncome" ~ "Normalized Exposure Index (HH Income)",
                    variable == "norm_exposure_index_WhiteBlack" ~ "Normalized Exposure Index (B. vs. W.)",
                    variable == "norm_exposure_index_WhiteHisp" ~ "Normalized Exposure Index (H. vs. W.)",
                    variable == "notInSchoolOrLf_prcnt_est_ages16to19" ~ "% of 16-19 year olds not in school or labor force",
                    variable == "nr_allSocialBeautyBusinesses_max_per10k" ~ "# of social support, social capital, and beauty businesses per 10k people (max)",
                    variable == "nr_allSocialBeautyBusinesses_min_per10k" ~ "# of social support, social capital, and beauty businesses per 10k people (min)",
                    variable == "nr_businesses_per10k" ~ "# of businesses per 10k people",
                    variable == "nr_homicides_max_3yr_avg_per100k" ~ "Homicide rate (max 3-year average)",
                    variable == "nr_homicides_max_5yr_avg_per100k" ~ "Homicide rate (max 5-year average)",
                    variable == "nr_homicides_max_per100k" ~ "Homicide rate (max)",
                    variable == "nr_homicides_min_3yr_avg_per100k" ~ "Homicide rate (min 3-year average)",
                    variable == "nr_homicides_min_5yr_avg_per100k" ~ "Homicide rate (min 5-year average)",
                    variable == "nr_homicides_min_per100k" ~ "Homicide rate (min)",
                    variable == "nr_new_businesses_per10k" ~ "Nr. of new businesses per 10k people",
                    variable == "nr_socialAssociations_max_per10k" ~ "Nr. of social capital associations per 10k people (max)",
                    variable == "nr_socialAssociations_min_per10k" ~ "Nr. of social capital associations per 10k people (min)",
                    variable == "nr_socialSupportServices_max_per10k" ~ "Nr. of social support associations per 10k people (max)",
                    variable == "nr_socialSupportServices_min_per10k" ~ "Nr. of social support associations per 10k people (min)",
                    variable == "pop_density" ~ "Population Density",
                    variable == "pop_nr_est" ~ "Population",
                    variable == "pop_prcnt_est_15to24_allRaces_m" ~ "% male 15-24",
                    variable == "pop_prcnt_est_15to24_b_m" ~ "% male 15-24 who are Black",
                    variable == "pop_prcnt_est_15to24_h_m" ~ "% male 15-24 who are Hispanic",
                    variable == "pop_prcnt_est_allAges_b" ~ "% Black",
                    variable == "pop_prcnt_est_allAges_h" ~ "% Hispanic",
                    variable == "pop_prcnt_est_allAges_w" ~ "% White",
                    variable == "poverty_prcnt_est_0to17" ~ "% of children in poverty",
                    variable == "poverty_prcnt_est_allAges" ~ "% in poverty",
                    variable == "president" ~ "% voted R. in most recent presidential election",
                    variable == "property_crime_per100k" ~ "Property Crime per 100k",
                    variable == "ratioBlackWhiteOvercrowding_diff_est" ~ "B. vs. W. overcrowding",
                    variable == "ratioHispWhiteOvercrowding_diff_est" ~ "H. vs. W. overcrowding",
                    variable == "ratioIncomeToPovertyBelow75_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: Below 0.75",
                    variable == "ratioIncomeToPoverty75to99_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: 0.75 to 0.99",
                    variable == "ratioIncomeToPoverty100to124_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: 1.00 to 1.24",
                    variable == "ratioIncomeToPoverty125to149_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: 1.25 to 1.49",
                    variable == "ratioIncomeToPoverty150to174_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: 1.5 to 1.74",
                    variable == "ratioIncomeToPoverty175to199_prcnt_est_povertyUniverse" ~ "% w/ ratio of income to poverty: 1.75 to 1.99",
                    variable == "receiveCpaSnapSSI_prcnt_est_ages17AndYounger" ~ "% of children who live in a household receiving CPA, SNAP, or SSI",
                    variable == "s_chamber_sd" ~ "Std. Dev. of Ideology in State Senate",
                    variable == "s_dem_sd" ~ "Std. Dev. of D. Ideology in State Senate",
                    variable == "s_distance" ~ "Mean Ideological Distance in State Senate",
                    variable == "s_rep_sd" ~ "Std. Dev. of R. Ideology in State Senate",
                    variable == "sen_chamber" ~ "Median Ideology in State Senate",
                    variable == "sen_dem" ~ "Median D. Ideology in State Senate",
                    variable == "sen_dem_mean" ~ "Mean D. Ideology in State Senate",
                    variable == "sen_rep" ~ "Median R. Ideology in State Senate",
                    variable == "sen_rep_mean" ~ "Mean R. Ideology in State Senate",
                    variable == "senate" ~ "% voted R. in most recent senate election",
                    variable == "shannon_index_scaled" ~ "Scaled Shannon Index (Race)",
                    variable == "shannon_index_scaled_edu" ~ "Scaled Shannon Index (Education)",
                    variable == "shannon_index_scaled_hhIncome" ~ "Scaled Shannon Index (HH Income)",
                    variable == "singleMom_prcnt_est" ~ "% of HHs headed by single mom",
                    variable == "singleParent_prcnt_est" ~ "% of HHs headed by single parent",
                    variable == "someCollege_prcnt_est_25older" ~ "% w/ some college education (highest)",
                    variable == "spatial_proximity_edu_b001" ~ "Spatial Proximity (Education, beta = 0.001)",
                    variable == "spatial_proximity_edu_b01" ~ "Spatial Proximity (Education, beta = 0.01)",
                    variable == "spatial_proximity_income_b001" ~ "Spatial Proximity (HH Income, beta = 0.001)",
                    variable == "spatial_proximity_income_b01" ~ "Spatial Proximity (HH Income, beta = 0.01)",
                    variable == "spatial_proximity_race_b001" ~ "Spatial Proximity (Race, beta = 0.001)",
                    variable == "spatial_proximity_race_b01" ~ "Spatial Proximity (Race, beta = 0.01)",
                    variable == "ur_prcnt_est_16andOlder" ~ "% unemployed",
                    variable == "urBlackToWhite_diff_est_16andOlder" ~ "B. vs. W. unemployed %",
                    variable == "urHispToWhite_diff_est_16andOlder" ~ "H. vs. W. unemployed %",
                    variable == "vacantHousingUnits_prcnt_est" ~ "% vacant housing units",
                    variable == "violent_crime_per100k" ~ "Violent Crime Per 100k",
                    variable == "yearMoved_median_est" ~ "Years Lived in Current Unit (Median)",
                    variable == "hhIncome_median_est" ~ "Median HH Income",
                    variable == "total_prison_adm_rate15to64" ~ "Prison Admission Rate",
                    T ~ variable
                )
        )
}
